### ISSUE TITLE
Corrigir "zenhub.core.APILimitError: Reached request limit to the API"

### ISSUE THREAD

**Issue by albertoueda** [MPMG-DCC-UFMG/F01-gerenciamento#1]
Solução temporária
---
Requisitar a atualização dos dados 2-3 vezes seguidas, aguardando o término de cada uma delas (~1min, via log).

Stacktrace
---
```bash
Atualizando dados de coletas...
[2022-05-04 12:19:54,642] ERROR in app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/mnt/hd0/ueda/venvs/mp/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/hd0/ueda/venvs/mp/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/hd0/ueda/venvs/mp/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/hd0/ueda/venvs/mp/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/mnt/hd0/ueda/venvs/mp/lib/python3.8/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/mnt/hd0/ueda/venvs/mp/lib/python3.8/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "app.py", line 300, in refresh
    main_etl.update_data_coletas(git_token, zh_token)
  File "/mnt/hd0/ueda/git/F01-gerenciamento/dashboard/main_etl.py", line 92, in update_data_coletas
    issues_epic_df, epics_id = transform_data.count_issues_epic(df, zh, repo_F01, repo_id)
  File "/mnt/hd0/ueda/git/F01-gerenciamento/dashboard/transform_data.py", line 8, in count_issues_epic
    issues_data = extract_data.get_data_epics(zh, epics_id, repo_id_f01)
  File "/mnt/hd0/ueda/git/F01-gerenciamento/dashboard/extract_data.py", line 12, in get_data_epics
    issues_data = {i: zh.get_epic_data(repo_id=repo_id, epic_id= i) for i in epics_id}
  File "/mnt/hd0/ueda/git/F01-gerenciamento/dashboard/extract_data.py", line 12, in <dictcomp>
    issues_data = {i: zh.get_epic_data(repo_id=repo_id, epic_id= i) for i in epics_id}
  File "/mnt/hd0/ueda/venvs/mp/lib/python3.8/site-packages/zenhub/core.py", line 181, in get_epic_data
    return self._get(url)
  File "/mnt/hd0/ueda/venvs/mp/lib/python3.8/site-packages/zenhub/core.py", line 89, in _get
    return self._parse_response_contents(response)
  File "/mnt/hd0/ueda/venvs/mp/lib/python3.8/site-packages/zenhub/core.py", line 66, in _parse_response_contents
    raise APILimitError("Reached request limit to the API. See API Limits.")
zenhub.core.APILimitError: Reached request limit to the API. See API Limits.
```

**Comment by albertoueda** [comment]
Relacionado:
* https://help.zenhub.com/support/solutions/articles/43000010374-api-rate-limiting
* https://github.com/ZenHubIO/API
